### ISSUE TITLE
Signing a transaction twice in a rowwith the consumer app

### ISSUE THREAD

**Issue by tjanez** [Zondax/ledger-oasis#68] opened 2020-11-25 17:24 UTC
Hi,

I encountered an issue with trying to sign two things in a row (in the same Go process).

It doesn't matter what they are, or whether I use Nano S or Nano X, the 2nd thing doesn't get sent to the Ledger app correctly and the CLI hangs waiting to read a response from the Ledger app.

Here is an example of Go code's logging output when trying to sign the same transaction with the Ledger app twice.

When doing the first signing, everything works ok.
These are the messages that are sent and responses that are received:

```
caller=app.go:385 msg=Sign message=05020000142c000080da010080000000800000008000000080
caller=app.go:391 msg=Sign err=null response=
caller=app.go:385 msg=Sign message=05020200a3636f617369732d636f72652f636f6e73656e7375733a20747820666f7220636861696e2033353565316431653334316532626466363164663838336661353864393037663262653361666338366162333039326132363161396166373362316133353639a463666565a26367617319099c66616d6f756e744064626f6479a166616d6f756e74417b656e6f6e636507666d6574686f646c7374616b696e672e4275726e
caller=app.go:391 msg=Sign err=null response=31da3c1747922d991bb5b8eca9081d40bd7849a5e96bb25a244c0baf7fe10cfd9a3f5a45aef1ad9db91fe05a16fc72e761c227b7c88c7db92372595a2a530208
```

To break these, up, there are 2 messages sent with the following content:

1. sign, init packet, path
2. sign, final packet, message chunk 0

When attempting to do the same thing the second time, the Go part hangs after sending the first message (sign, init packet, path):

```
caller=app.go:385 msg=Sign message=05020000142c000080da010080000000800000008000000080
```

The second message is never sent as the Go code waits for the response after the first message.

Only after unplugging the Ledger device, the CLI continues with:

```
caller=app.go:391 msg=Sign err="Cannot deserialize the packet. Header information is missing." response=
caller=address.go:112 msg="failed to sign burn tx" wallet_id=null index=0 err="ledger/oasis: failed to sign: Cannot deserialize the packet. Header information is missing."
```

This is expected, since the communication was broken and the receiving buffer contained 0 bytes, hence the error in [ledger-go's `DeserializePacket()` code](https://github.com/Zondax/ledger-go/blob/73b5de1b6d24646daacdde374fb9b21b85289012/apduWrapper.go#L105-L112):

```go
func DeserializePacket(
	channel uint16,
	buffer []byte,
	sequenceIdx uint16) (result []byte, totalResponseLength uint16, err error) {

	if (sequenceIdx == 0 && len(buffer) < 7) || (sequenceIdx > 0 && len(buffer) < 5) {
		return nil, 0, errors.New("Cannot deserialize the packet. Header information is missing.")
	}
	...
```

**Comment by ftheirs** [comment] 2023-11-14 14:45
I'll close this issue since I was not able to reproduce this on the device!

**Closed by ftheirs** 2023-11-14 14:45 UTC
Labels: bug, External, P2-Mid
