### ISSUE TITLE
Intermittent error when signing transaction using js library

### ISSUE THREAD

**Issue by calvinzhou-rockx** [Zondax/ledger-oasis#75] opened 2021-01-20 02:51 UTC
Hi,

We used the ledger js library to do transaction signing to Ledger, there is an intermittent error message:
```
‘First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.’
```
It happens randomly and if user retry a few times, the error gone and return a correct signature, the same error was reported both in https://oasis-wallet.rockx.com and https://anthem.chorus.one/ for Oasis ledger 

Thanks

**Comment by rllola** [comment] 2021-01-20 09:05
Without the ability to reproduce the error it will be a bit difficult to help you.

The error seems to come from a `Buffer.from` conversion. Are you sure you are passing a correct path/message ? Is it happening after the user has validated the transaction on his ledger ?

**Comment by calvinzhou-rockx** [comment] 2021-01-20 09:28
> Without the ability to reproduce the error it will be a bit difficult to help you.
> 
> The error seems to come from a `Buffer.from` conversion. Are you sure you are passing a correct path/message ? Is it happening after the user has validated the transaction on his ledger ?

As mentioned, the transaction is validated, if user re-submit the same transaction, it's high chance to get a correct response from ledger

The error is returned from sign function in index.js, what I want to know is what kind of scenario would cause this kind of errors? 
It could be caused by the async api call and the data is not ready before user click to sign the transaction

**Comment by rllola** [comment] 2021-01-20 09:52
It could be caused by many thing. That's why I would need to know if the error appears before the transaction is displayed on the ledger or after it has been displayed on the ledger. It would help to identify if the error is happening before the message being send to the ledger or after.

What is most likely to cause it is a bad path or message as we haven't encountered this kind of error in our tests.

**Comment by calvinzhou-rockx** [comment] 2021-01-20 16:18
> It could be caused by many things. That's why I would need to know if the error appears before the transaction is displayed on the ledger or after it has been displayed on the ledger. It would help to identify if the error is happening before the message being send to the ledger or after.
> 
> What is most likely to cause it is a bad path or message as we haven't encountered this kind of error in our tests.

It's difficult for me to replicate this after I tried multi-times, only one thing can be confirmed is the error happened before the message being sent to the ledger

**Comment by rllola** [comment] 2021-01-21 11:12
Ok. The best I can do is adding some more checks on the data passed. It would at least give a more comprehensible error or discard this hypothesis.

**Comment by calvinzhou-rockx** [comment] 2021-01-21 14:29
> Ok. The best I can do is adding some more checks on the data passed. It would at least give a more comprehensible error or discard this hypothesis.

OK, please let me know when the logger is ready and I'll pull out the code, hopefully it helps, thanks

**Comment by StreamOfMaya** [comment] 2021-06-03 13:07
We were never able to reproduce the error.  We will close this issue if we do not hear back from you within 3 weeks.

**Comment by ftheirs** [comment] 2022-11-25 11:55
Closing this issues cause we didn't hear back from @calvinzhou-rockx. Please, feel free to add more info or reopen the issue 😄

**Closed by ftheirs** 2022-11-25 11:55 UTC
Labels: NeedsInfo, P2-Mid
